import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-black`}
      >
        <nav className="w-full flex justify-center m-5 flex-center items-center gap-6 text-center">
          <Link href={"/"}>
            Page d&apos;accueil
          </Link>
          <Link href={"/statique"}>
            Page statique
          </Link>
          <Link href={"/actualites/test-article"}>
            Page test
          </Link>
          <Link href={"actualites/404"}>
            Page 404
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
